CREATE TABLE [TABLE_NAME] (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  hash VARCHAR(36) NOT NULL,
  domain VARCHAR(255) NOT NULL,
  hits INT(11) NOT NULL,
  timestamp INT(11) NOT NULL,
  PRIMARY KEY (id)
) [TABLE_CHARSET];